#!/bin/bash
# Quick reference for Vercel environment variable cleanup

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Vercel Environment Variables - Cleanup Checklist            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Go to: https://vercel.com/dashboard → Your Project → Settings → Environment Variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ DELETE THESE (unused Redis/KV variables):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  [ ] UPSTASH_REDIS_REST_TOKEN"
echo "  [ ] UPSTASH_REDIS_REST_URL"
echo "  [ ] swagstore_KV_URL"
echo "  [ ] swagstore_KV_REST_API_READ_ONLY_TOKEN"
echo "  [ ] swagstore_REDIS_URL"
echo "  [ ] swagstore_KV_REST_API_TOKEN"
echo "  [ ] swagstore_KV_REST_API_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ KEEP THESE (actively used Firebase variables):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ NEXT_PUBLIC_FIREBASE_API_KEY"
echo "  ✓ NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "  ✓ NEXT_PUBLIC_FIREBASE_PROJECT_ID (check: NO quotes!)"
echo "  ✓ NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "  ✓ NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "  ✓ NEXT_PUBLIC_FIREBASE_APP_ID"
echo "  ✓ NEXT_PUBLIC_ROOT_DOMAIN"
echo "  ✓ FIREBASE_PROJECT_ID"
echo "  ✓ FIREBASE_CLIENT_EMAIL"
echo "  ✓ FIREBASE_PRIVATE_KEY"
echo "  ✓ SITE_ADMIN_TOKEN (if used)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  CRITICAL: Check NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Value should be:  store-hub-1ty89"
echo "NOT:             \"store-hub-1ty89\""
echo ""
echo "If it has quotes, edit it and remove them!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After cleanup, Vercel will automatically redeploy."
echo "Run './scripts/verify-production.sh' to verify everything works!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
